# Generated by Django 4.0.5 on 2022-07-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=30)),
                ('method', models.CharField(choices=[('get', 'GET request'), ('post', 'POST request')], max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
